name: FactionMasterInvitationImprove
author: ShockedPlot7560
version: 2.0.1
api: 4.0.0
main: ShockedPlot7560\FactionMasterInvitationImprove\FactionMasterInvitationImprove
src-namespace-prefix: ShockedPlot7560\FactionMasterInvitationImprove
depend: ["FactionMaster"]
description: "Extension which improve invitation system of FactionMaster"
